version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: put password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - specif folder:/var/lib/mysql